Repository OpenThaiGPT/openthaigpt-pretraining, pull requests merged in 2023-05, with the labels that each got.

#97 docs(all): add PR Template
  .github/pull_request_template.md
  docs/PR_NAMING.md
Labels: documentation

#67 feat(model): setup tokenizer training pipeline
  .gitignore
  src/model/openthaigpt_pretraining_model/spm_trainer.py
  tests/model/spm_trainer_test.py
Labels: enhancement

#103 fix(model): resolve flake8 error
  src/model/openthaigpt_pretraining_model/spm_trainer.py
  tests/model/spm_trainer_test.py
Labels: bug

#102 feat(model): Convert NanoGPT Lion Experiment to Multi GPU
  src/model/openthaigpt_pretraining_model/models/nanoGPT/model.py
  src/model/openthaigpt_pretraining_model/optimizers/lion/utils.py
  src/model/scripts/experiments/lion_experiment/README.md
Labels: enhancement

#87 feat(model): add LLaMa Tokenizer Supported Thai Token
  .vscode/extensions.json
  .vscode/settings.json
  src/model/openthaigpt_pretraining_model/llama_thai_tokenizer/__init__.py
  src/model/openthaigpt_pretraining_model/llama_thai_tokenizer/constants.py
  src/model/openthaigpt_pretraining_model/llama_thai_tokenizer/merge.py
  src/model/openthaigpt_pretraining_model/llama_thai_tokenizer/thai_tokenizer/trained_bpe.model
  src/model/openthaigpt_pretraining_model/llama_thai_tokenizer/tokenizer.py
  src/model/pyproject.toml
  src/model/scripts/llama_thai_tokenizer/README.md
  src/model/scripts/llama_thai_tokenizer/merge_tokenizer.py
  src/model/scripts/llama_thai_tokenizer/time_inference_check.py
  tests/model/llama_thai_tokenizer_test.py
Labels: enhancement

#96 perf(model): Add xFormers in GPTJ
  src/data/pyproject.toml
  src/model/openthaigpt_pretraining_model/gptj/gptj_model_xformers.py
  src/model/pyproject.toml
  tests/model/gptj_test.py
Labels: enhancement

#99 GPTJ Tokenizer Supported Thai Token
  .gitignore
  src/model/__init__.py
  src/model/openthaigpt_pretraining_model/GPTJ_TH_tokenizer/__init__ .py
  src/model/openthaigpt_pretraining_model/GPTJ_TH_tokenizer/constants.py
  src/model/openthaigpt_pretraining_model/GPTJ_TH_tokenizer/merge.py
  src/model/openthaigpt_pretraining_model/GPTJ_TH_tokenizer/tokenizer.py
  src/model/scripts/gptj_thai_tokenizer/README.md
  src/model/scripts/gptj_thai_tokenizer/merge_tokenizers.py
  tests/model/GPTJ_th_tokenizer_test.py
Labels: enhancement

#105 fix(all): linter action not working when pr from fork
  .github/workflows/lint.yaml
Labels: bug

#104 feat(model): setup data preprocessing pipeline
  src/model/openthaigpt_pretraining_model/tokenizers/data_preprocessing.py
  src/model/openthaigpt_pretraining_model/tokenizers/spm_trainer.py
  tests/model/spm_trainer_test.py
Labels: enhancement

#111 build(all): prevent concurrent workflow on same pr and branch
  .github/workflows/lint.yaml
  .github/workflows/test_core.yaml
  .github/workflows/test_data.yaml
  .github/workflows/test_evaluation.yaml
  .github/workflows/test_model.yaml
Labels: enhancement

#112 build(model): add docker env
  .devcontainer/devcontainer.json
  README.md
  docker/Dockerfile
Labels: documentation, enhancement

#119 feat(model): add adam8bit optim
  src/model/openthaigpt_pretraining_model/optimizers/lion/utils.py
  src/model/pyproject.toml
Labels: enhancement

#158 Setup repo dvc
  .dvc/.gitignore
  .dvc/config
  .dvcignore
  src/model/openthaigpt_pretraining_model/llama_thai_tokenizer/thai_tokenizer/.gitignore
  src/model/openthaigpt_pretraining_model/llama_thai_tokenizer/thai_tokenizer/trained_bpe.model
  src/model/openthaigpt_pretraining_model/llama_thai_tokenizer/thai_tokenizer/trained_bpe.model.dvc
Labels: enhancement
